### ISSUE TITLE
SOFTWARE and VERSION

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/OI-Imaging-JRA#10]
We should add a software (or algorithm) and software version keywords in `IMAGE-OI OUTPUT PARAM` :
- `SOFTWARE`
- `SOFT_VER`

**Comment by FerreolS** [comment]
Up to now, there is no way to know which software was used to create an OI-Interface image. We could use an heuristic to infer it but I think, it should be in the standard somehow

**Comment by jsy1001** [comment]
The ESO standard is:

PROCSOFT  Indicates the reduction software system including its version number used 
to produce this data product.

**Comment by FerreolS** [comment]
Ok.  PROCSOFT keyword may be already used by the reduction pipeline. As an example, PIONIER oifits files contains in the primary header :
```PROCSOFT= 'pndrs_v3.52'        / Data reduction software and version```
Is setting the algorithm in PROCSOFT keyword in IMAGE-OI OUTPUT PARAM hdu is sufficiently clear?

**Comment by jsy1001** [comment]
I think its clear from the context of being in a different hdu.

**Comment by GillesDuvert** [comment]
there is already VERSION ?

**Comment by FerreolS** [comment]
There in no eso keyword for version. The version number seems to be usually added to the software name in the PROCSOFT keyword

**Comment by jsy1001** [comment]
I've implemented PROCSOFT for bsmem.

**Comment by buthanoid** [comment]
I created an issue for OImaging https://github.com/JMMC-OpenDev/oimaging/issues/96

**Comment by GillesDuvert** [comment]
What would be the version of Wisard at any moment? At the moment it is 3.2.2 . This is not an internal Wisard number, it is a Github release number triggered by Laurent. It would be nice to have PROCSOFT set to the release number 'automatically'. Since the number is a string, I figure a GH script could insert the actual release number in the Wisard "code", as it is not compiled but just a procedure.
Any other solution leads to a discrepancy between PROCSOFT and the only number availble around, the GH release number. Or am I confused?

**Comment by FerreolS** [comment]
Ok. That seems doable, it is probably just a few  lines to add in the dockerfile : https://github.com/JMMC-OpenDev/oimaging-uws-server/blob/master/runtime/docker/oiservices/Dockerfile

**Comment by jsy1001** [comment]
We should document this usage of PROCSOFT in the specification document.
